### PR TITLE
vendor: update dependency package

### PR DESCRIPTION
**Pull request by q384566678**
Update `runtime-spec` to `rc5` and some other packages.

Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
@opencontainers/image-tools-maintainers PTAL

**Comment by stevvooe** [comment]
Rebase.

**Comment by q384566678** [comment]
Rebased.

**Comment by q384566678** [comment]
PTAL

**Comment by q384566678** [comment]
@stevvooe @vbatts @coolljt0725 PTAL.

**Comment by stevvooe** [comment]
LGTM

**Comment by coolljt0725** [comment]
LGTM

**Pull request merged**
