### PR TITLE
updating CoC link and adding security section

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

https://github.com/opencontainers/org/issues/3

### CODE REVIEW

**Comment by cyphar** [comment]
Please squash your commits.

**Comment by vsoch** [comment]
@cyphar what about this one - where I've done the PR from master? Is the only way to start afresh?

**Comment by vsoch** [comment]
I'm getting a "noop"

image

**Comment by cyphar** [comment]
You need to do `git rebase -i <what it was based on>`.

**Comment by vsoch** [comment]
I didn't check out a new branch here, I commit to master, so I'll just do this one over.

**Comment by vsoch** [comment]
This is now a ghost pull request - the tree it comes from is nothing more than a memory!

**Comment by cyphar** [comment]
Sure -- for the record you could've done it with `git rebase -i origin/master` or by passing the commit ID instead with `git rebase -i $commit`.

**Pull request closed without merging**
