### PR TITLE
MAINTAINERS: add Aleksa Sarai

### PR DESCRIPTION
**Pull request by cyphar**
Much of the work I've done in umoci is effectively rewriting parts of
image-tools so that they are better designed and stable. I feel very
strongly that most (if not all) of umoci should live within this
project.

As such, I feel that I'm sufficiently familiar with all of the many
implementation details necessary to correctly and sanely implement the
OCI image specification.

Signed-off-by: Aleksa Sarai <asarai@suse.de>

- [ ] @brendandburns
- [x] @coolljt0725
- [ ] @jbouzane
- [x] @jonboulle
- [x] @jstarks
- [x] @philips
- [x] @stevvooe
- [x] @vbatts
- [x] @xiekeyang

### CODE REVIEW

**Comment by caniszczyk** [comment]
Just as a note you have contributed to image-tools in the past:
https://github.com/opencontainers/image-tools/commits?author=cyphar

cc: @opencontainers/image-tools-maintainers

**Comment by cyphar** [comment]
/me is writing a mail on the ML about some of my more radical ideas. In particular, I would love it if we could turn `umoci` into an OCI project, and then extend `umoci` to have all of the features that spawned the requirement for `image-tools`.

**Comment by cyphar** [comment]
Before we merge this, there is some discussion about the future of `umoci` and `image-tools` that we should hash out on the mailing list first. I'll send a mail about it this afternoon/evening.

**Comment by vbatts** [comment]
SGTM

**Comment by stevvooe** [comment]
@cyphar You beat me to it!

LGTM

**Comment by stevvooe** [comment]
I've updated the commit to track the progress of the vote!

Good luck!

**Comment by vbatts** [comment]
LGTM

**Comment by jstarks** [comment]
LGTM

**Comment by philips** [comment]
LGTM

**Comment by coolljt0725** [comment]
LGTM

**Comment by xiekeyang** [comment]
LGTM

**Comment by jonboulle** [comment]
LGTM

**Comment by caniszczyk** [comment]
7/9 votes is good enough to meet the 2/3 requirement.

Welcome @cyphar as an image-tools maintainer!

**Pull request merged**
