### PR TITLE
Hello world!

### PR DESCRIPTION
**Pull request by runcom**
This is moving from OCI/image-spec to this new repository - the relevant commit to review is https://github.com/opencontainers/image-tools/commit/f0a6243701b8b6407116386d9d52ea89915586fc (this commit is also splitting oci-image-tool in 3 new binaries as per https://github.com/opencontainers/image-spec/issues/296)

Please, do add Travis CI.

This is keeping all the history from OCI/image-spec - I'll move out the issues from the spec tomorrow morning.

If something isn't really super correct and doesn't block this PR - I believe we can get this PR in and re-iterate in the following days.

@vbatts @philips PTAL

### CODE REVIEW

**Comment by wking** [comment]
On Wed, Sep 14, 2016 at 11:39:20AM -0700, Antonio Murdaca wrote:
> This is moving from OCI/image-spec to this new repository…

How was this branch created?  I expect we want to merge
project-template and image-spec, and then remove the spec-only stuff.
Preserving project-template's commit history makes life easier for Git
when we pull in future project-templates updates (e.g. if
opencontainers/project-template#18 lands).  Preserving the image-spec
history makes it easy to audit the split ;).

**Comment by runcom** [comment]
This was created from the image-spec

**Comment by philips** [comment]
@wking I am guessing git filter-branch

**Comment by runcom** [comment]
@wking the split is just 1 commit not sure what you need to audit exactly

**Comment by runcom** [comment]
Also, I don't have commit access to this repo so if anyone would/could, he can pick up image-spec, apply my latest commit from this PR and push force to this repo to preserve commit history. Otherwise github isn't letting me create a PR from totally different branch with nothing in common.

**Comment by wking** [comment]
On Wed, Sep 14, 2016 at 12:01:57PM -0700, Antonio Murdaca wrote:
> Otherwise github isn't letting me create a PR from totally different
> branch with nothing in common.

You can merge this repo into your external history (that's what I did
in opencontainers/project-template#3).

**Comment by runcom** [comment]
@wking how about now?

**Comment by philips** [comment]
LGTM

**Comment by caniszczyk** [comment]
FYI: I also just enabled Travis CI here too

**Comment by runcom** [comment]
> FYI: I also just enabled Travis CI here too

thanks Chris!

**Comment by wking** [comment]
On Wed, Sep 14, 2016 at 01:01:22PM -0700, Antonio Murdaca wrote:
> @wking how about now?

9554306 looks pretty good to me.  It's just missing a merge from
project-template [1].

[1]: https://github.com/opencontainers/tob/blob/8997b1aa221b3b61d4305bede41c257b879bdeeb/proposals/tools.md#governance-and-releases

**Comment by runcom** [comment]
@wking I merged project-templace as well now

**Comment by wking** [comment]
On Wed, Sep 14, 2016 at 02:19:23PM -0700, Antonio Murdaca wrote:
> @wking I merged project-templace as well now

Looks pretty good to me.  Minor nits:

* 6a8fd3b6f adds a ‘TODO(runcom)’ to HACKING.md.  I'd rather just drop
  HACKING.md now that it's mostly empty.  You may want to put your
  tweak-commit after all the merges to make rerolling around those
  merges.
* 6a8fd3b6f adds ‘tools’ to the Makefile but does not document it in
  the ‘help’ target.
* 6a8fd3b6f uses oci-validate, etc., but I would prefer
  oci-image-validate, etc. to avoid conflicts or ambiguity with
  ocitools (which, since opencontainers/runtime-tools#212 is
  installing oci-runtime-tool).

**Comment by runcom** [comment]
@wking @philips @vbatts should be good to go

**Comment by vbatts** [comment]
loads of DCO missing, and whitespace checks fail. and the build fails (`make tools`).
...
but LGTM as a first PR ;-)

**Comment by runcom** [comment]
> and the build fails (make tools).

ooh I'll fix this one before merging (weird)

@vbatts about the DCO and whitespaces, not sure what should I do.

**Comment by philips** [comment]
LGTM

@caniszczyk can you just override the DCO thing, those mistakes were made long ago and not really fixable.

P.S. Can we get rid of the DCO, it is sooooo silly.

**Comment by vbatts** [comment]
LGTM

**Comment by runcom** [comment]
`make tools` has been fixed though!

**Pull request merged**
