### PR TITLE
Add Travis CI badge to README

### PR DESCRIPTION
**Pull request by caniszczyk**
https://travis-ci.org/opencontainers/image-tools

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
:tada:

**Comment by jonboulle** [comment]
lgtm

**Comment by jonboulle** [comment]
@caniszczyk do we need the LGTM bot here?

**Comment by philips** [comment]
LGTM

**Pull request merged**
