### PR TITLE
manpage: modify OPTIONS to FLAGS

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by xiekeyang** [comment]
I think change from `flag` to `option` is OK, but this should be accordant to tools usage.

**Comment by Mashimiao** [comment]
I think the change does not make manpage to be not accordant with tools usage.

**Comment by xiekeyang** [comment]
I mean help message of tools had better to be changed accordingly(`flag` to `option`), to be like
```
$ ./oci-image-validate --help
Usage:  oci-image-validate FILE... [options...]
Options: ...
```

**Comment by Mashimiao** [comment]
Though I want to change all of `flags` to `options` which I think is more common.
But as cobra use flags instead of options as default, it seems better to change `OPTIONS` to `FLAGS` in manpage.
@xiekeyang  PTAL

**Comment by xiekeyang** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
