### PR TITLE
Delete does not exist properties

### PR DESCRIPTION
**Pull request by q384566678**
Make the following changes according to https://github.com/opencontainers/image-spec/pull/495
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by coolljt0725** [comment]
We need to bump the image-spec first

**Comment by q384566678** [comment]
@coolljt0725 updated.Thank you so much for your suggestion.
@xiekeyang @stevvooe PTAL

**Comment by coolljt0725** [comment]
@q384566678  AFAIK, these being removed field does in `v1.0.0-rc3`,   I think we should wait the https://github.com/opencontainers/image-spec/pull/495 being land on next release and then bump the image-spec.

**Comment by stevvooe** [comment]
LGTM

**Comment by xiekeyang** [comment]
LGTM

**Pull request merged**
