### PR TITLE
Add bash-completion for oci-image-tool

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by Mashimiao** [comment]
ping @opencontainers/image-tools-maintainers   without this fix, we can't execute `make install` currently

**Comment by vbatts** [comment]
LGTM

**Comment by q384566678** [comment]
LGTM

**Comment by q384566678** [comment]
@caniszczyk It looks like my current `LGTM` is not working, can you solve this problem? Thank you.

**Comment by coolljt0725** [comment]
LGTM

**Pull request merged**
