### PR TITLE
vendor: update image-spec to rc6

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
@cyphar @stevvooe @vbatts @coolljt0725 @jonboulle PTAL.

**Comment by q384566678** [comment]
@opencontainers/image-tools-maintainers I think I need to get some response.

**Comment by coolljt0725** [comment]
should we make sure that `image-tool` work with rc5 well and then we release a `image-tool`, after that we update the image-spec to rc6 ?

**Comment by q384566678** [comment]
> should we make sure that image-tool work with rc5 well and then we release a image-tool, after that we update the image-spec to rc6 ?

I think it is basically in line with rc5, only one validation of index, which I think will be more convenient after rc6.  I think some of the verification (including imageLayout) in the update to rc6 will be better implemented.

**Comment by q384566678** [comment]
@coolljt0725 @xiekeyang @cyphar @vbatts @stevvooe `Image-tool` has been released v0.2.0 version, can be updated to rc6?

**Comment by q384566678** [comment]
re-ping @opencontainers/image-tools-maintainers.

**Comment by xiekeyang** [comment]
I think it is OK, what other maintainers think?

**Comment by coolljt0725** [comment]
LGTM

**Comment by stevvooe** [comment]
LGTM

**Pull request merged**
