### PR TITLE
Update dependencies to work with new layer media type

### PR DESCRIPTION
**Pull request by glestaris**
Since https://github.com/opencontainers/image-spec/pull/347 the layer media type has been changed. This commit bumps the image-spec and dependencies.

### CODE REVIEW

**Comment by wking** [comment]
On Tue, Oct 25, 2016 at 01:43:45PM -0700, George Lestaris wrote:
>     M vendor/github.com/opencontainers/runtime-spec/specs-go/config.go (44)
>     M vendor/github.com/opencontainers/runtime-spec/specs-go/state.go (2)
>     M vendor/github.com/opencontainers/runtime-spec/specs-go/version.go (2)

Can we pin runtime-spec in glide.yaml?  I don't think the current repo
is stable enough to leave our dependency floating (with
incompatible-Go changes between Go changes breaking the current
patch-level comparison [1,2]).  And the runtime-spec versions are
versioning the config format anyway (opencontainers/runtime-spec#523),
so we shouldn't expect them to apply to the Go bindings.

[1]: https://github.com/opencontainers/image-tools/blob/f24d27b5e62acb27a688e36cbac13902bfb75234/glide.yaml#L9
[2]: https://glide.readthedocs.io/en/latest/versions/#tilde-range-comparisons-patch

**Comment by runcom** [comment]
is this a duplicate of https://github.com/opencontainers/image-tools/pull/69 ?

**Comment by wking** [comment]
Yes.

**Comment by glestaris** [comment]
I'll close this one since #69 seems to work better with @wking's request :)

**Pull request closed without merging**
