### PR TITLE
Bump version v0.2.0

### PR DESCRIPTION
**Pull request by xiekeyang**
#142 from Mashimiao/tfix-format
#144 from q384566678/up-validate
#140 from Mashimiao/fix-help-info
#148 from q384566678/up-runtime-spec
#132 from q384566678/fix-glide
#139 from Mashimiao/add-bash-completion
#135 from erikh/fix-tar-files
#145 from q384566678/zhou-hao
#134 from erikh/fix-logger
#137 from q384566678/value-test
#138 from jonboulle/master
#133 from Mashimiao/makefile-add-missing-evars
#130 from q384566678/zz-test
#136 from squeed/tar-streams
#128 from q384566678/fix-man
#127 from q384566678/reandme-fix
#126 from ddysher/update-vendor
#124 from xiekeyang/logrus
#103 from q384566678/main-test
#123 from q384566678/fix-list
#121 from q384566678/bump-version
#119 from Mashimiao/fix-ignore

### CODE REVIEW

**Comment by q384566678** [comment]
LGTM

**Comment by cyphar** [comment]
@q384566678 You need to respond with your LGTM on the mailing list thread for this PR before it will get merged.

**Comment by xiekeyang** [comment]
@opencontainers/image-tools-maintainers according to vote result https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/C2kFyvZQ_6A, so far 8/11 maintainers agree this release. PTAL. Thanks.

**Comment by q384566678** [comment]
Bump.

**Comment by coolljt0725** [comment]
LGTM

**Comment by wking** [comment]
Does someone want to push a `v0.2.0` tag for 7f277bf?

**Comment by xiekeyang** [comment]
@wking I'm doing.

**Comment by xiekeyang** [comment]
push tag to https://github.com/opencontainers/image-tools/tree/v0.2.0

**Comment by wking** [comment]
On Mon, Jul 10, 2017 at 11:38:44PM -0700, xiekeyang wrote:
> push tag to https://github.com/opencontainers/image-tools/tree/v0.2.0

I see a v0.2.0 *branch* [1], but not a v0.2.0 tag [2].  I think you
want to delete the branch and create a tag.  Something like:

  $ git branch -D v0.2.0
  $ git push origin :v0.2.0
  $ git tag -s v0.2.0 7f277bf
  $ git push origin v0.2.0

and then write some release notes in there (e.g. see [3]).

[1]: https://github.com/opencontainers/image-tools/branches
[2]: https://github.com/opencontainers/image-tools/tags
[3]: https://github.com/opencontainers/image-tools/releases/tag/v0.1.0

**Comment by q384566678** [comment]
ping @xiekeyang

**Comment by q384566678** [comment]
@xiekeyang Can you fix this ?

**Comment by xiekeyang** [comment]
Sorry, fixing...

**Comment by xiekeyang** [comment]
Sorry to late, released on https://github.com/opencontainers/image-tools/releases/tag/v0.2.0

**Pull request merged**
