### PR TITLE
image: add validation to index.json

### PR DESCRIPTION
**Pull request by q384566678**
Can't just verify the format.

Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
ping @opencontainers/image-tools-maintainers

**Comment by q384566678** [comment]
@coolljt0725 @vbatts @stevvooe @xiekeyang PTAL

**Comment by coolljt0725** [comment]
LGTM

**Comment by xiekeyang** [comment]
LGTM

**Pull request merged**
