### PR TITLE
main.go:Modify some information

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by xiekeyang** [comment]
Previous description should be acceptable, because it want to unpack source file to the rootfs.
Refer to https://github.com/opencontainers/image-tools/pull/47#discussion_r84600849

**Comment by q384566678** [comment]
updated,But this way, and [this note](https://github.com/opencontainers/image-tools/blame/master/cmd/oci-create-runtime-bundle/main.go#L41) will not contradict each other, in addition，I think this is need to modify the error message

**Comment by xiekeyang** [comment]
It looks goo to me.

**Comment by wking** [comment]
c8145385 looks fine to me, although I'm fine with the previous language too.

**Comment by q384566678** [comment]
@stevvooe  @vbatts  @philips PTAL

**Comment by coolljt0725** [comment]
LGTM

**Comment by xiekeyang** [comment]
LGTM

**Pull request merged**
