### PR TITLE
cmd: Modify the assignment of parameters

### PR DESCRIPTION
**Pull request by q384566678**
This modification can avoid the absence of default values.

Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by xiekeyang** [comment]
I'd rather to set value at statement of `v`, like,
```go
v := bundleCmd{root : rootfs, ref : ... }
```
And, I think `if` condition might be necessary for those who has no default value.

**Comment by vbatts** [comment]
what happens if those variables are _not_ set? will it panic?

**Comment by xiekeyang** [comment]
@vbatts 
> what happens if those variables are not set? will it panic?

it doesn't cause panic. The value should be empty for string type, `false` for bool type, and so on.

**Comment by q384566678** [comment]
> And, I think if condition might be necessary for those who has no default value.

@xiekeyang The if statement performs only the assignment action, and the previous assignment has been repeated, so I do not think so.

**Comment by xiekeyang** [comment]
LGTM

**Comment by coolljt0725** [comment]
LGTM

**Pull request merged**
