### PR TITLE
update to golang 1.11

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
@opencontainers/image-tools-maintainers PTAL

**Comment by xiekeyang** [comment]
@q384566678 
commit 4775f434bc5a5f1a55505b2adddf0101d3dc46b2 might better to be another PR, right?
To `update to golang 1.11` one, I'm OK.

**Comment by q384566678** [comment]
@xiekeyang The previous mistakes were all before go1.10, and I don't think there is any change. So I think it is better to have two commits in the same pr.

**Comment by q384566678** [comment]
I added some instructions to the commit.　@xiekeyang PTAL

**Comment by xiekeyang** [comment]
Got it!

LGTM

**Pull request merged**
