### PR TITLE
MAINTAINERS: add Zhou Hao

### PR DESCRIPTION
**Pull request by q384566678**
I have been in this community for nearly six months, and has been working for the development of this community. In order to better serve this community, I would like to apply to become MAINTAINER. I hope you can agree. Thank you all. @philips @brendandburns @jbouzane @jstarks @jonboulle @stevvooe @vbatts @xiekeyang @coolljt0725 @cyphar 

Here's my contribution:
https://github.com/opencontainers/image-tools/commits?author=q384566678

Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by caniszczyk** [comment]
sounds fair to me, @opencontainers/image-tools-maintainers would have to approve

**Comment by vbatts** [comment]
LGTM

**Comment by vbatts** [comment]
(also thank you for your contributions!)

**Comment by coolljt0725** [comment]
LGTM

**Comment by philips** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM

**Comment by jstarks** [comment]
LGTM

**Comment by brendandburns** [comment]
LGTM.



________________________________

**Comment by xiekeyang** [comment]
LGTM

**Comment by caniszczyk** [comment]
7/10 @opencontainers/image-tools-maintainers approve, this is good enough for a merge

thanks all!

welcome @q384566678

**Comment by philips** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

**Pull request merged**
