### PR TITLE
Increase the authentication type

### PR DESCRIPTION
**Pull request by q384566678**
When I use the validate function, and verify if it is through the automatic judgment function judgment type, do not know what is the type of validation, I think in this authentication type prompt better.

Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
@vbatts @philips @xiekeyang @coolljt0725 PTAL

**Comment by Mashimiao** [comment]
it's better to clear tell user the type belongs to which file

**Comment by q384566678** [comment]
@vbatts @xiekeyang @stevvooe @coolljt0725 PTAL

**Comment by stevvooe** [comment]
Why are still putting so much work into autodetection?

**Comment by q384566678** [comment]
> Why are still putting so much work into autodetection?
@stevvooe Here is only to increase the type of authentication information. So, what is the problem?

**Pull request closed without merging**
