### PR TITLE
fix unpack command line

### PR DESCRIPTION
**Pull request by xiekeyang**
Signed-off-by: xiekeyang <xiekeyang@huawei.com>

### CODE REVIEW

**Comment by runcom** [comment]
lgtm (ianam)

**Comment by vbatts** [comment]
LGTM

**Comment by wking** [comment]
fb5d04cb looks good to me.

**Comment by wking** [comment]
On Thu, Sep 22, 2016 at 09:40:09AM -0700, Vincent Batts wrote:
> LGTM

PullApprove has not blessed this with a green token, although it's
currently configured to look at image-spec-maintainers [1].  Does it
still need be turned on for this repo?  cc @caniszczyk.

[1]: https://github.com/opencontainers/image-tools/blob/721ba581955c2b8ce1184d7492ed5e3f5ba3e1d4/.pullapprove.yml#L9

**Pull request merged**
