### PR TITLE
version： bump to v0.3.0

### PR DESCRIPTION
**Pull request by q384566678**
#172 from Mashimiao/cleanup-bundle
#171 from Mashimiao/rm-dup-error
#170 from q384566678/string-fix
#168 from q384566678/fix-annnoation
#165 from q384566678/go-report
#163 from q384566678/image-spec-update
#160 from q384566678/image-spec-up
#158 from q384566678/makefile-fix
#157 from q384566678/image-test-fix
#156 from q384566678/glid-up
#155 from xiekeyang/bump-version
#150 from q384566678/up-image-spec
#141 from Mashimiao/autodetect-add-more-type
#84   from q384566678/test-layout
#51   from q384566678/test-mlist

Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by xiekeyang** [comment]
You can add the no. of PRs to the commit editing:

#141
#158
#172
#156
#170
#171
#157
#168
#165
#163
#84
#160
#150
#155

**Comment by q384566678** [comment]
updated.

**Comment by vbatts** [comment]
LGTM

**Comment by q384566678** [comment]
@opencontainers/image-tools-maintainers According to vote result https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/eXPEJHDvYIg, so far 5 maintainers agree this release. 
PTAL. Thanks.

**Comment by coolljt0725** [comment]
LGTM

**Pull request merged**
