### PR TITLE
image: code optimization

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by Mashimiao** [comment]
LGTM

**Comment by q384566678** [comment]
@coolljt0725 PTAL

**Comment by coolljt0725** [comment]
why don't use `v1.Image` as a object?

**Comment by q384566678** [comment]
This problem is discussed [here,](https://github.com/opencontainers/image-tools/pull/144#discussion-diff-115256424R54) so I made the code changes. I also modified the manifest related code.

**Comment by coolljt0725** [comment]
LGTM

**Comment by q384566678** [comment]
ping @Mashimiao

**Pull request merged**
