### PR TITLE
fix help info for --type option

### PR DESCRIPTION
**Pull request by Mashimiao**
oci-image-tool-validate is not correct any more, fix it.

Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by vbatts** [comment]
I wonder if i can just use os.Args[0] or similar? Otherwise LGTM

**Comment by q384566678** [comment]
https://github.com/opencontainers/image-tools/pull/140/commits/2c4fef6f73ba0b52e3c0b257410bb854fee4ac7f looks good to me.

**Comment by coolljt0725** [comment]
LGTM

**Comment by q384566678** [comment]
LGTM

**Comment by q384566678** [comment]
LGTM

**Pull request merged**
