### PR TITLE
README.md: fix example

### PR DESCRIPTION
**Pull request by hongchaodeng**
Signed-off-by: Hongchao Deng <hongchaodeng1@gmail.com>

Otherwise it will error:
```
cannot save image with empty image.ref.name
```

Ref: https://github.com/projectatomic/skopeo/issues/446

### CODE REVIEW

**Comment by Mashimiao** [comment]
You need to add a Signed-off-by: line to your commit

**Comment by hongchaodeng** [comment]
@Mashimiao Already added but still not passed.

**Comment by Mashimiao** [comment]
That's because your commit's author is not the same as signed-off-by

**Comment by hongchaodeng** [comment]
Fixed.
Thanks for your advice.

**Comment by jonboulle** [comment]
lgtm

**Comment by q384566678** [comment]
The same question in man folder(`oci-image-tool-*.md`), can you fix it together?

**Comment by coolljt0725** [comment]
@hongchaodeng  as @q384566678  mentioned, can you also fix https://github.com/opencontainers/image-tools/blob/master/man/oci-image-tool-create.1.md#examples 
https://github.com/opencontainers/image-tools/blob/master/man/oci-image-tool-unpack.1.md#examples
https://github.com/opencontainers/image-tools/blob/master/man/oci-image-tool-validate.1.md#examples ?

**Comment by hongchaodeng** [comment]
fixed

**Comment by coolljt0725** [comment]
LGTM

**Comment by q384566678** [comment]
LGTM

**Pull request merged**
