### PR TITLE
Fixes #175 by referring to logrus by its lower-case name.

### LINKED ISSUE #175: Use github.com/sirupsen/logrus instead of github.com/Sirupsen/logrus
Since image-tools refers to the logrus package with a capital letter it cannot be imported together with another package that uses the lower-case logrus package name since go build returns a case-insensitive import collision.

Thus unfortunately for instance I cannot import image-tools together with github.com/containers/image.

To solve this issue the glide dependency and corresponding imports should be updated to use the lower-case logrus package name since it has changed recently. According to https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276 the name change will not be reverted and most projects are already using the lower-case variant.

logrus references must be updated in the following files:
* glide.yaml
* image/manifest.go
* image/manifest_test.go
* cmd/oci-image-tool/main.go

### PR DESCRIPTION
**Pull request by mgoltzsche**
References of github.com/Sirupsen/logrus have been rewritten to
github.com/sirupsen/logrus to avoid case-insensitive import collisions when
importing this project together with other projects that already refer to
logrus using its lower-case package name.

logrus references have been updated manually in the following files:
* glide.yaml
* image/manifest.go
* image/manifest_test.go
* cmd/oci-image-tool/main.go

glide updated some more files.
Build, lint and test have been run successfully.

Background: https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276

Please be aware that this fix may cause problems in other projects that already use image-tools and still refer to github.com/Sirupsen/logrus but finally all projects that use the latter should be adjusted to use the lower-case name.

Signed-off-by: Max Goltzsche <max.goltzsche@gmail.com>

### CODE REVIEW

**Comment by q384566678** [comment]
Please follow the [prompts](https://travis-ci.org/opencontainers/image-tools/jobs/269783948#L218) to modify PR.

**Comment by q384566678** [comment]
@mgoltzsche please update.

**Comment by mgoltzsche** [comment]
Whitespace removed. Sorry for the delay.

**Comment by q384566678** [comment]
LGTM

**Comment by q384566678** [comment]
ping  @coolljt0725

**Comment by q384566678** [comment]
cc @coolljt0725

**Comment by coolljt0725** [comment]
LGTM

**Pull request merged**
