### PR TITLE
image_test.go: Improve the test content

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
@xiekeyang @coolljt0725 PTAL

**Comment by coolljt0725** [comment]
@q384566678  we need to bump the image-spec first before we have this changes, because `Labels` is not in the image-spec which the image-tool currently used.

**Comment by q384566678** [comment]
@coolljt0725 I do not quite understand the meaning of `bump`, can you please explain to me? thanks.

**Comment by coolljt0725** [comment]
@q384566678  https://github.com/opencontainers/image-tools/pull/69 is an example of bump

**Comment by q384566678** [comment]
@coolljt0725 Since #102  has been merged, the `bump` is complete.

**Comment by coolljt0725** [comment]
LGTM

**Comment by xiekeyang** [comment]
LGTM

**Pull request merged**
