### PR TITLE
maintainers: add two folks

### PR DESCRIPTION
**Pull request by vbatts**
The image-tools has received heavy focus and contribution from Xie
Keyang (@xiekeyang) and Lie Jitang (@coolljt0725) from Huawei.

I propose add them so we can keep the progress rolling on the tools
repo!

Signed-off-by: Vincent Batts vbatts@hashbangbash.com

### CODE REVIEW

**Comment by jbouzane** [comment]
LGTM

**Comment by philips** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM

**Comment by caniszczyk** [comment]
LGTM

**Comment by philips** [comment]
LGTM

**Comment by wking** [comment]
This has passed outside of the formal “five business days” voting
window [1], although I'm not sure how seriously we take that
restriction [2].  Currently the count is under the ⅔ requirement [3]
by two LGTMs.  @brendandburns, @jonboulle, @jstarks, @stevvooe, care
to chime in?

@coolljt0725, @xiekeyang, you should probably chime in as well with
“I'm fine becoming a maintainer” or “No thanks” or some such so folks
can tell you're not being sucked in against your will ;).

[1]: https://github.com/opencontainers/image-tools/blame/0a1e5dc0c9b67619d46bd8cbcc948bda1b143b27/MAINTAINERS_GUIDE.md#L105
[2]: https://github.com/opencontainers/runtime-tools/pull/239#issuecomment-253405601
[3]: https://github.com/opencontainers/image-tools/blame/0a1e5dc0c9b67619d46bd8cbcc948bda1b143b27/MAINTAINERS_GUIDE.md#L102

**Comment by coolljt0725** [comment]
thanks all, I'm fine become a maintainer to help maintain the image-tool repo :)

**Comment by xiekeyang** [comment]
It is my pleasure and I'm happy to become maintainer of image-tool repo. Thanks so much!

**Comment by caniszczyk** [comment]
I invited @xiekeyang @coolljt0725 to the team, so they should be all set once they accept :)

**Comment by vbatts** [comment]
\o/

**Comment by wking** [comment]
On Tue, Nov 08, 2016 at 08:35:28AM -0800, Chris Aniszczyk wrote:
> I invited @xiekeyang @coolljt0725 to the team, so they should be all
> set once they accept :)

I'm not against them being accepted, but I think their addition is
still short by two LGTMs [1].  Were there additional votes made
outside this PR?

[1]: https://github.com/opencontainers/image-tools/pull/54#issuecomment-257775310

**Comment by jstarks** [comment]
LGTM

**Pull request merged**
